apiVersion: v1
kind: Pod
metadata:
  name: aioquic-http3-pod
  labels:
    app: aioquic-http3 # Label for the Service to select this Pod
spec:
  containers:
    - name: aioquic-http3-container
      image: aucslab/aioquic-http3-server:latest
      imagePullPolicy: IfNotPresent # Pulls if not present locally (good for development/testing)
                                    # Use 'Always' if you want to ensure the latest image from the registry
                                    # Use 'Never' if you only want to use a locally built image and never pull
      ports:
        - containerPort: 4433
          protocol: UDP # Essential for HTTP/3 traffic
      env:
        - name: MY_NODE_NAME # The name of the node this Pod is scheduled on
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      args:
        - "python3"
        - "examples/http3_server.py"
        - "--certificate"
        - "ssl_cert.pem" # Assumes cert is baked into the image at /app
        - "--private-key"
        - "ssl_key.pem"  # Assumes key is baked into the image at /app
      

---
apiVersion: v1
kind: Service
metadata:
  name: aioquic-http3-service
  labels:
    app: aioquic-http3
spec:
  selector:
    app: aioquic-http3 # This matches the label on your Pod to select it
  ports:
    - protocol: UDP       # Explicitly specify UDP for HTTP/3
      port: 4433          # The port on the Service (internal to the cluster)
      targetPort: 4433    # The port the container inside the Pod listens on
      # Kubernetes will automatically assign a random nodePort here
      name: http3-udp
  type: NodePort          # Exposes the Service on each Kubernetes Node's IP at a random NodePort
